name: blurhash_dart
version: 1.0.2
homepage: https://github.com/justacid/blurhash-dart
description: >
  A pure dart implementation of the BlurHash algorithm.
  This package provides both an encoder and a decoder,
  as well as some utility extensions.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  image: ^3.0.1

dev_dependencies:
  test: ^1.16.5
