name: blurhash_dart
description: A pure dart implementation of blurhash
version: 0.1.0
author: Tobias Schwackenhofer
homepage: https://github.com/justacid/blurhash-dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  test: ^1.12.0
