name: blurhash_dart
description: A pure dart implementation of blurhash
version: 0.2.1
homepage: https://github.com/justacid/blurhash-dart

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  test: ^1.12.0
  image: ^2.1.12
